FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git
WORKDIR /src
RUN git clone https://github.com/AnFuran/docker-reach.git . && \
    CGO_ENABLED=0 GOOS=linux go build -o /gateway ./cmd/gateway

FROM alpine:latest
RUN apk add --no-cache iptables iproute2
COPY --from=builder /gateway /usr/local/bin/gateway

EXPOSE 9999 9998
CMD ["gateway"]
